# Note: This file is only used for Atlantis local development
version: "3.8"
services:
    ngrok:
        image: wernight/ngrok:latest
        ports:
        - 4040:4040
        environment:
            # https://dashboard.ngrok.com/get-started/your-authtoken
            NGROK_AUTH: 2EEFRAlW9HXH5icafJ3h6UWPN2m_5HGpP6JjJwtRHEXKjMxwm
            NGROK_PROTOCOL: http
            NGROK_PORT: atlantis:4141
        depends_on:
        - atlantis
    redis:
        image: redis:6.2-alpine
        restart: always
        ports:
        - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass test123
        volumes: 
        - redis:/data
    atlantis:
        depends_on:
        - redis
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
        - 4141:4141
        - 2345:2345
        volumes:
            - /Users/joel.llacer/.ssh:/.ssh
            - /Users/joel.llacer/projects/opensource/atlantis/:/atlantis/src
        # Contains the flags that atlantis uses in env var form
        env_file:
            - ./atlantis.env
        command: [ "/root/go/bin/dlv", "exec", "/usr/local/bin/atlantis", "server", "-l", "0.0.0.0:2345", "--headless", "--api-version", "2" ]

volumes:
    redis:
        driver: local